// Code generated by hertz generator.

package main

import (
	"Exvs/http/biz/handler/Exvs"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	register(h)
	Exvs.InitGenericClient()

	h.Spin()
}
